### ISSUE TITLE
feat: 添加启动器

### ISSUE THREAD

**Issue by llxlr** [BioArchLinux/wsl#1]
[wsldl](https://github.com/yuk7/wsldl) 是用 golang 编写的 WSL 通用启动器，我已经提交了 BioArchLinux 的图标。它易于编译和使用，只需要把现有的 [bioarchlinux-20220801.tar](https://mirrors.sdu.edu.cn/bioarchlinux/wsl/bioarchlinux-20220801.tar) 重命名为 rootfs.tar，再用 gzip 把 rootfs.tar 压缩为 rootfs.tar.gz 文件，把编译好的 BioArch.exe 和 rootfs.tar.gz 放到同一目录下：

![Snipaste_2022-08-02_23-12-10](https://user-images.githubusercontent.com/33483752/182409899-910651bb-94c6-4065-ae02-d11f843cd37f.png)
![Snipaste_2022-08-02_23-15-41](https://user-images.githubusercontent.com/33483752/182410564-504e33d1-c671-44e1-8669-14739e3a6da0.png)

双击 BioArch.exe 就能安装了。两个大小加起来才 147MB，小巧方便。

这是我编译好的 [BioArch.exe](https://github.com/BioArchLinux/wsl/files/9243506/BioArch.zip)

**Comment by starsareintherose** [comment]
抱歉没有看见，能不能制作个脚本，我用 systemd service timer 定期在 linux 服务器上做

**Comment by starsareintherose** [comment]
Thanks, I have used this and updated the readme
